sudo: false

env:
  global:
  - ANT_OPTS=-Xmx1024m

language: java
jdk:
  - oraclejdk8
env:
  - SCRIPT="ant -Dhalt.on.plugin.error=true -f build/build.xml clean compile"
  - SCRIPT="ant -Dhalt.on.plugin.error=true -f build/build.xml clean test"
  - SCRIPT="ant -Dhalt.on.plugin.error=true -f build/build.xml clean openfire"
script: $SCRIPT
install: true
